# -*- coding: utf-8 -*-
"""Kasir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cnvPqhcoJXS6rHxG9gn6oeC09IEIc3R
"""

from datetime import datetime
import random

# ================================
# DATA BARANG (DIAN)
# ================================
menu = {
    'BR01': {'nama':'Beras', 'harga':12000},
    'MB01': {'nama':'Minyak goreng botol', 'harga':15000},
    'MC01': {'nama':'Minyak goreng cup', 'harga':5000},
    'MI01': {'nama':'Mie instan', 'harga':3500},
    'TT01': {'nama':'Tepung terigu', 'harga':11000},
    'TA01': {'nama':'Telur ayam', 'harga':28000},
    'GP01': {'nama':'Gula pasir', 'harga':11000},
    'GR01': {'nama':'Garam', 'harga':4000},
    'TC01': {'nama':'Teh celup sachet', 'harga':2000},
    'KI01': {'nama':'Kopi instan sachet', 'harga':2000},
    'SK01': {'nama':'Susu kental manis sachet', 'harga':3000},
    'AM01': {'nama':'Air mineral', 'harga':4000},
    'SC01': {'nama':'Sabun mandi cair', 'harga':12000},
    'SB01': {'nama':'Sabun mandi batang', 'harga':4000},
    'SM01': {'nama':'Shampo sachet', 'harga':2000},
    'DB01': {'nama':'Detergen bubuk', 'harga':5000},
    'PG01': {'nama':'Pasta gigi', 'harga':12000},
    'TS01': {'nama':'Tisu', 'harga':6000},
    'PL01': {'nama':'Pembersih lantai', 'harga':16000},
    'OB01': {'nama':'Obat nyamuk bakar', 'harga':6000},
    'OS01': {'nama':'Obat nyamuk semprot', 'harga':20000},
    'KA01': {'nama':'Korek api', 'harga':2000},
    'BT01': {'nama':'Baterai', 'harga':10000}
}

# ================================
# TAMPILAN MENU BARANG
# ================================
def sistem():
  def tampil_menu():
      print(f"\n{'DAFTAR BARANG TOKO':^60}")
      print("="*60)
      print(f"{'Kode':<10}{'Nama Barang':<30}{'Harga':<15}")
      print("-"*60)
      for kode, info in menu.items():
          print(f"{kode:<10}{info['nama']:<30}Rp {info['harga']:<10}")
      print("-"*60)
      print("="*60)

  # ================================
  # DISPLAY TOKO
  # ================================
  print(f"\n{'TOKO TIKUM MIKASA':^60}")
  print(f"{'GROSIR SEMBAKO':^60}")
  print(f"{'Jl Kapten Suparman 39':^60}")
  print(f"{'Potrobangsan, Magelang Utara':^60}")
  print(f"{'Kota Magelang, Jawa Tengah, 56116':^60}")
  print("-"*60)

  waktu = datetime.now().strftime("%d.%m.%Y - %H:%M:%S")
  print(f"Waktu\t\t: {waktu}")
  kasir = input("Nama Kasir\t: ")
  print("Ketik 'stop' untuk selesai")
  print("-"*60)

  tampil_menu()

  # ================================
  # PEMBELIAN (ANGGUN)
  # ================================
  keranjang = []
  total = 0

  while True:
      kode = input("\nKode Barang : ").upper()

      if kode == "STOP":
          break

      if kode not in menu:
          print("Kode barang tidak ditemukan!")
          continue

      try:
          jumlah = int(input("Jumlah      : "))
      except:
          print("Jumlah harus angka!")
          continue

      nama = menu[kode]["nama"]
      harga = menu[kode]["harga"]
      subtotal = harga * jumlah
      total += subtotal

      keranjang.append({
          "kode" : kode,
          "nama" : nama,
          "harga" : harga,
          "jumlah" : jumlah,
          "subtotal" : subtotal
      })

      print(f"\n{kode}\t{nama}")
      print(f"\t{jumlah} x Rp {harga} = Rp {subtotal}")
      print(f"Total sementara: Rp {total}")

  # ================================
  # DISKON (KYADEVI)
  # ================================
  if total >= 500000:
      diskon = 0.25
  elif total >= 400000:
      diskon = 0.20
  elif total >= 300000:
      diskon = 0.15
  elif total >= 200000:
      diskon = 0.10
  elif total >= 100000:
      diskon = 0.05
  else:
      diskon = 0

  nilai_diskon = int(total * diskon)
  total_bayar = total - nilai_diskon

  # ================================
  # PEMBAYARAN
  # ================================
  print("\nTotal Belanja :", total)
  print("Diskon        :", int(diskon*100),"%")
  print("Total Bayar   :", total_bayar)

  bayar = int(input("Uang Bayar    : "))
  kembali = bayar - total_bayar
  print("Kembalian     :", kembali)

  # ================================
  # STRUK BELANJA (PUTRI)
  # ================================
  print("\n" + "="*60)
  print(f"{'TOKO TIKUM MIKASA':^60}")
  print(f"{'GROSIR SEMBAKO':^60}")
  print(f"{'Jl. Kapten Suparman 39':^60}")
  print(f"{'Potrobangsan, Magelang Utara':^60}")
  print(f"{'Kota Magelang, Jawa Tengah, 56116':^60}")
  print("-"*60)

  no_transaksi = random.randint(100000,999999)
  print(f"No Penjualan    : {no_transaksi}")
  print(f"Waktu Penjualan : {waktu}")
  print(f"Nama kasir      : {kasir}")
  print("-"*60)

  for item in keranjang:
      print(f"{item['kode']}\t{item['nama']}")
      print(f"\t{item['jumlah']} x Rp{item['harga']}\t= Rp{item['subtotal']}\n")

  print("-"*60)
  print(f"Total        : Rp{total}")
  print(f"Anda Hemat   : Rp{nilai_diskon}")
  print(f"Jumlah Total : Rp{total_bayar}")
  print(f"Dibayar      : Rp{bayar}")
  print(f"Kembali      : Rp{kembali}")
  print("="*60)
  print(f"{' Barang yang sudah dibeli tidak dapat dikembalikan ':^60}")
  print(f"{' Terimakasih Anda sudah tidak BON ':^60}")
  print("="*60)
  print(f"{'TERIMA KASIH ATAS KUNJUNGAN ANDA':^60}")
  print("="*60)

while True:
  pakai = input("Gunakan sistem? (Yes/No): ").lower()
  if pakai == "yes":
    sistem()
    break
  elif pakai == "no":
    print("Sistem tidak dijalankan.")
    break
  else:
    print("Masukkan hanya Yes/No!")